### ISSUE TITLE
can not build  in iMac18,3[Catalina10.15.4]  debug Error: Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65

### ISSUE THREAD

**Issue by passionofvc** [uport-project/uport-mobile#215]
uport-mobile can not build in iMac.

**Desktop (please complete the following information):**
 - OS: [iMac18,3(Catalina10.15.4])]
```
$ node --version
v10.20.0
```

**Additional context**
compile log
```
$ git clone https://github.com/uport-project/uport-mobile.git
$ yarn global add react-native-cli 
$ yarn
$ react-native run-ios --verbose

The following build commands failed:
	CompileC /Users/yamada/blockchain/uport/uport-mobile/ios/build/uPortMobile/Build/Intermediates.noindex/RNFirebase.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseAnalytics.o RNFirebase/analytics/RNFirebaseAnalytics.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

debug Error: Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening uPortMobile.xcworkspace

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/yamada/blockchain/uport/uport-mobile/ios/build/uPortMobile/Build/Intermediates.noindex/RNFirebase.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseAnalytics.o RNFirebase/analytics/RNFirebaseAnalytics.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at ChildProcess.buildProcess.on.code (/Users/yamada/blockchain/uport/uport-mobile/node_modules/@react-native-community/cli/build/commands/runIOS/runIOS.js:246:16)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

```
in yarn.lock the react-native-firebase version is 5.6.0.
```
react-native-firebase@^5.2.5:
   version "5.6.0"
   resolved "https://registry.yarnpkg.com/react-native-firebase/-/react-native-firebase-5.6.0.tgz#6f6123f53cb73477915dd55c55f3e1de91db38d2"
   integrity sha512-I+o3zNLdIz4pxWTCSZH70M1BcPl+SdqKQfurOT0sWcaMSL2ecDqVy0PCTmN7ORt7/Z879Er6PLgA/psjArQlmw==
   dependencies:
     opencollective-postinstall "^2.0.0"
     prop-types "^15.7.2"
```

**Comment by jasheal** [comment]
@passionofvc We recommend you use [daf-mobile](https://github.com/uport-project/daf-mobile) and our [daf](https://github.com/uport-project/daf) framework as we are in the process of deprecating this repo.
